### ISSUE TITLE
angular payment_data

### ISSUE THREAD

**Issue by SasoriOlkof** [jrief/djangoshop-stripe#9] opened 2018-01-25 17:28 UTC
hi.

The stripe form gives me an error when accessing the property of angular "payment_data"
I see the error but I do not see where the form declares it, I do not know what is expected of this property nor do I have much idea of angular jejeje

maybe you can help me, what is in the repository is the version you use?

![image](https://user-images.githubusercontent.com/7782720/35402141-e92a05f0-01fb-11e8-9b32-01cf2f962d79.png)

thank you very much :)

**Comment by jrief** [comment] 2018-01-26 06:36
which versions of django-shop and djangoshop-stripe are you using?

**Comment by SasoriOlkof** [comment] 2018-01-26 08:02
first, thanks for your interest :)

django-shop, I am using the current version of the repository, (0.12?)
djangoshop-stripe==0.12

and if it can help you:
``appdirs==1.4.3
beautifulsoup4==4.6.0
bitpay==2.3.3
bs4==0.0.1
certifi==2017.11.5
cffi==1.9.1
chardet==3.0.4
cmsplugin-filer==1.1.3
cryptography==1.7.2
defusedxml==0.5.0
dj-database-url==0.4.1
Django==1.10.7
django-admin-sortable2==0.6.15
django-allauth==0.32.0
django-angular==2.0.0
django-appconf==1.0.2
django-bootstrap-form==3.2.1
django-bootstrap3==9.0.0
django-bower==5.2.0
django-braces==1.11.0
django-classy-tags==0.8.0
django-cms==3.4.5
django-colorfield==0.1.14
django-compressor==2.2
django-djconfig==0.4.0
django-extensions==1.7.5
django-filer==1.3.0
django-filter==1.1.0
django-formtools==2.1
django-fsm==2.6.0
django-fsm-admin==1.2.4
django-haystack==2.5.0
django-infinite-scroll-pagination==0.1.3
django-invitations==1.9
django-ipware==1.1.6
django-machina==0.5.3
django-mailer==1.2.2
django-mptt==0.8.7
django-npm==1.0.0
django-ordered-model==1.3.0
django-parler==1.8
django-polymorphic==1.3
django-post-office==3.0.3
django-postman==3.5.1
django-redis-cache==1.7.1
django-redis-sessions==0.6.1
django-rest-auth==0.9.2
django-sass-processor==0.5.5
django-sekizai==0.10.0
Django-Select2==5.11.1
django-treebeard==4.1.2
django-widget-tweaks==1.4.1
djangocms-admin-style==1.2.7
djangocms-attributes-field==0.1.2
djangocms-bootstrap3==0.3.1
djangocms-cascade==0.15.4
djangocms-column==1.7.0
djangocms-googlemap==1.0.1
djangocms-installer==0.9.3
djangocms-link==2.0.3
djangocms-snippet==1.9.2
djangocms-style==2.0.1
djangocms-text-ckeditor==3.5.0
djangocms-video==2.0.3
djangorestframework==3.6.3
djangoshop-stripe==0.12
docopt==0.6.2
drf-haystack==1.6.1
easy-thumbnails==2.5
ecdsa==0.13
elasticsearch==1.7.0
Fabric3==1.13.1.post1
hiredis==0.2.0
html5lib==0.9999999
idna==2.6
jsonfield==2.0.2
libsass==0.12.3
lockfile==0.12.2
Markdown==2.6.11
markdown2==2.3.3
mistune==0.7.1
mysqlclient==1.3.10
oauthlib==2.0.2
olefile==0.44
packaging==16.8
paramiko==2.1.1
Pillow==4.3.0
pluggy==0.3.1
py==1.4.30
pyasn1==0.1.9
pycparser==2.17
Pygments==2.0.2
PyMySQL==0.7.11
pyparsing==2.2.0
python-dateutil==2.6.0
python-openid==2.2.5
python3-openid==3.1.0
pytz==2017.2
randstr==0.1.2
rcssmin==1.0.6
redis==2.10.6
requests==2.18.4
requests-oauthlib==0.8.0
rjsmin==1.0.12
simplejson==3.10.0
six==1.11.0
stripe==1.53.0
tzlocal==1.3
unicode-slugify==0.1.3
Unidecode==0.4.21
urllib3==1.22
virtualenv==13.1.2
Whoosh==2.7.0``

**Comment by SasoriOlkof** [comment] 2018-01-26 08:10
in which template or js would you have to declare the "payment_data"? if it is a problem of versions and you know how to say where, I could implement it in my version

**Comment by jrief** [comment] 2018-01-26 08:45
but currently the official version is still 0.11. Could you please use the latest 0.12 versions from GitHub. Both django-shop and djangoshop-stripe

**Comment by SasoriOlkof** [comment] 2018-01-26 09:37
Ok, I have put django-shop==0.11.3 and djangoshop-stripe==0.3.4 and it works fine.
I do not know why I thought that django-shop==0.11.X was not compatible with python 3.6, but works fine :)

but, when using djangoshop-stripe==0.12 with the current version of the repositiory django-shop or with django-shop==0.11.3 we have that error

**Comment by jrief** [comment] 2018-01-26 14:00
this is because the API changed slightly between version 0.11 and 0.12
I'm sorry for that

**Comment by SasoriOlkof** [comment] 2018-01-26 14:59
do not apologize if you have done much hehehe.

thanks for everything, for me we can close this thread

**Comment by jrief** [comment] 2020-05-16 15:35
I can not reproduce this error in my current version, so closing this issue.

**Closed as completed by jrief** 2020-05-16 15:35 UTC
